import subprocess
from pathlib import Path


class SolutionRunner:
    def __init__(self, solution_path):
        """
        Initializes the runner for a solution.

        Args:
            solution_path (str or Path): Path to the solution file.
        """
        self.solution_path = Path(solution_path)
        if not self.solution_path.exists():
            raise FileNotFoundError(f"Solution not found: {self.solution_path}")

    def run(self, input_data):
        """
        Executes the solution with the provided input.

        Args:
            input_data (str): Input data for the solution.

        Returns:
            str: Output generated by the solution.
        """
        process = subprocess.run(
            ["python", self.solution_path],
            input=input_data,
            text=True,
            capture_output=True,
        )
        if process.returncode != 0:
            raise RuntimeError(
                f"Error executing solution {self.solution_path}: {process.stderr}"
            )
        return process.stdout.strip()
